Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []

if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_SID_BARE_TEST'):
    src += Glob('*.c')

group = DefineGroup('test-efuse', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
