Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_QEP_DRV_TEST'):
    src = Glob('*.c')

group = DefineGroup('test-qep', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
